trigger:
- main

name: Deploy Pipeline

variables:
  azureServiceConnection: 'demo-flt.ado.apimPropagation'
  resourceGroupName: 'demo-flt.ado.apimPropagation'
  templateFile: './Deployment/main.bicep'

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Install mytool as a dotnet tool'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global Swashbuckle.AspNetCore.Cli --version 6.5.0'

- task: DotNetCoreCLI@2
  displayName: 'Restore project'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: 'Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o Publish'
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: 'WorkingFolder'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    csmFile: '$(templateFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
