trigger:
- main

name: Deploy Pipeline

variables:
  azureServiceConnection: 'demo-flt.ado.apimPropagation'
  resourceGroupName: 'demo-flt.ado.apimPropagation'
  templateFile: './Deployment/main.bicep'

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Install Swashbuckle.AspNetCore.Cli v6.5.0'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global Swashbuckle.AspNetCore.Cli --version 6.5.0'

- task: DotNetCoreCLI@2
  displayName: 'Restore project'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: 'Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)\Publish'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PowerShell@2
  inputs:
    script: 'swagger tofile --output $(Build.ArtifactStagingDirectory)\openapi.json $(Build.ArtifactStagingDirectory)\Publish\flt.ado.apimPropagation.Api.dll v1'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    csmFile: '$(templateFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
